blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blog_posts, name='all_blog_posts'),
    path('<int:blog_id>/', views.detail, name='detail')

]

myportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='portfolio/media')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.


def all_blog_posts(request):
    blog = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blog_posts.html', {'blogs': blog})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    project = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': project})

blog/templates/blog/all_blog_posts.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Emmanuel has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
    <div class="row justify-content-center my-3">
    <div class="col-md-10">
        <a href="{% url 'blog:detail' blog.id %}">
        <h2>{{ blog.title }}</h2>
        </a>
        <h5 class="text-muted">{{ blog.date|date:'M d Y' }}</h5>
        <p class="text-justify">{{ blog.description|striptags|truncatechars:250 }}</p>
    </div>
    </div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

    <h2 class="text-center mt-4"> {{ blog.title }} </h2>
    <b>
        <p>{{ blog.date | date:'F jS Y'}}</p>
    </b>
    <p class="text-justify">{{ blog.description | safe }}</p>    

{% endblock  %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

     <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% comment %} custom style {% endcomment %}
    <link rel="stylesheet" href="{% static 'portfolio/style.css' %}">

    {% comment %} //fonts.googleapis.com/css {% endcomment %}
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">


    <title>Some page</title>

    </head>
     <body>

    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">

        {% comment %} <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="logique's Logo"> {% endcomment %}

        <span class="lead">Ujah Emmanuel</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/ujah-emmanuel/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/islogique" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blog_posts' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="container">
    {% block content %}{% endblock %}
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
</body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

        <h1 class="mt-5"> Ujah Emmanuel </h1>
        <hr>

        <div class="row justify-content-center my-3">
            <div class="col-5">
                <img src="{% static 'portfolio/ujah.jpg' %}" class="img-fluid">
            </div>
        </div>

        <div class="row justify-content-center mb-3">
            <div class="col-md-9 text-center">
                <p id="hometext" >Ujah Emmanuel is a skilled software engineer with wide range of experience on web and mobile development 😊</p>
            </div>
        </div>


    <div class="row">
            {% for project in projects %}
                <div class="col-lg-4 col-md-6">

                    {% if project.url %}

                    <a href="{{ project.url }}">
                        <img src="{{ project.image.url }}" class="img-fluid mb-2">
                    </a>
                    
                    {% else %}

                    <img src="{{ project.image.url }}" class="img-fluid mb-2">

                    {% endif %}

                    <h3>{{ project.title }}</h3>
                    <p>{{ project.description }}</p>
            </div>

        {% endfor %}
    </div>

{% endblock %}